// Deterministic mock dataset used when CRICKETDATA_API_KEY is missing.
// Mirrors the shape of CricAPI v1 responses (after light normalization in service.js)
// so the rest of the stack — controllers, client, UI — works identically with or without a key.

const TEAMS = {
  IND: { name: 'India', shortname: 'IND', img: 'https://flagcdn.com/w160/in.png' },
  AUS: { name: 'Australia', shortname: 'AUS', img: 'https://flagcdn.com/w160/au.png' },
  ENG: { name: 'England', shortname: 'ENG', img: 'https://flagcdn.com/w160/gb-eng.png' },
  PAK: { name: 'Pakistan', shortname: 'PAK', img: 'https://flagcdn.com/w160/pk.png' },
  NZ:  { name: 'New Zealand', shortname: 'NZ', img: 'https://flagcdn.com/w160/nz.png' },
  SA:  { name: 'South Africa', shortname: 'SA', img: 'https://flagcdn.com/w160/za.png' },
  SL:  { name: 'Sri Lanka', shortname: 'SL', img: 'https://flagcdn.com/w160/lk.png' },
  WI:  { name: 'West Indies', shortname: 'WI', img: 'https://flagcdn.com/w160/jm.png' },
  BAN: { name: 'Bangladesh', shortname: 'BAN', img: 'https://flagcdn.com/w160/bd.png' },
  AFG: { name: 'Afghanistan', shortname: 'AFG', img: 'https://flagcdn.com/w160/af.png' },
  IRE: { name: 'Ireland', shortname: 'IRE', img: 'https://flagcdn.com/w160/ie.png' },
  ZIM: { name: 'Zimbabwe', shortname: 'ZIM', img: 'https://flagcdn.com/w160/zw.png' },
};

const t = (k) => ({ ...TEAMS[k] });

const now = () => new Date();
const hoursAgo = (h) => new Date(Date.now() - h * 3600 * 1000).toISOString();
const hoursAhead = (h) => new Date(Date.now() + h * 3600 * 1000).toISOString();

const MATCHES = [
  {
    id: 'mock-live-1',
    name: 'India vs Australia, 3rd ODI',
    matchType: 'ODI',
    status: 'India need 48 runs in 36 balls',
    venue: 'M. A. Chidambaram Stadium, Chennai',
    date: hoursAgo(3),
    dateTimeGMT: hoursAgo(3),
    teams: ['India', 'Australia'],
    teamInfo: [t('IND'), t('AUS')],
    score: [
      { r: 287, w: 9, o: 50, inning: 'Australia Innings' },
      { r: 240, w: 6, o: 44, inning: 'India Innings' },
    ],
    series_id: 'mock-series-1',
    seriesName: 'Border-Gavaskar ODI Series',
    matchStarted: true,
    matchEnded: false,
  },
  {
    id: 'mock-live-2',
    name: 'England vs Pakistan, 2nd T20I',
    matchType: 'T20I',
    status: 'England need 12 runs in 9 balls',
    venue: 'Edgbaston, Birmingham',
    date: hoursAgo(1),
    dateTimeGMT: hoursAgo(1),
    teams: ['England', 'Pakistan'],
    teamInfo: [t('ENG'), t('PAK')],
    score: [
      { r: 178, w: 6, o: 20, inning: 'Pakistan Innings' },
      { r: 167, w: 4, o: 18.3, inning: 'England Innings' },
    ],
    series_id: 'mock-series-2',
    seriesName: 'England vs Pakistan T20I Series',
    matchStarted: true,
    matchEnded: false,
  },
  {
    id: 'mock-live-3',
    name: 'New Zealand vs South Africa, 1st Test, Day 3',
    matchType: 'Test',
    status: 'Stumps - South Africa lead by 154 runs',
    venue: 'Hagley Oval, Christchurch',
    date: hoursAgo(8),
    dateTimeGMT: hoursAgo(8),
    teams: ['New Zealand', 'South Africa'],
    teamInfo: [t('NZ'), t('SA')],
    score: [
      { r: 312, w: 10, o: 98.4, inning: 'South Africa 1st Innings' },
      { r: 268, w: 10, o: 84.2, inning: 'New Zealand 1st Innings' },
      { r: 110, w: 4, o: 32, inning: 'South Africa 2nd Innings' },
    ],
    series_id: 'mock-series-3',
    seriesName: 'NZ vs SA Test Series',
    matchStarted: true,
    matchEnded: false,
  },
  {
    id: 'mock-upcoming-1',
    name: 'Sri Lanka vs Bangladesh, 1st ODI',
    matchType: 'ODI',
    status: 'Match starts soon',
    venue: 'R. Premadasa Stadium, Colombo',
    date: hoursAhead(3),
    dateTimeGMT: hoursAhead(3),
    teams: ['Sri Lanka', 'Bangladesh'],
    teamInfo: [t('SL'), t('BAN')],
    score: [],
    series_id: 'mock-series-4',
    seriesName: 'SL vs BAN ODI Series',
    matchStarted: false,
    matchEnded: false,
  },
  {
    id: 'mock-upcoming-2',
    name: 'West Indies vs Afghanistan, 2nd T20I',
    matchType: 'T20I',
    status: 'Match starts in 6 hours',
    venue: 'Kensington Oval, Bridgetown',
    date: hoursAhead(6),
    dateTimeGMT: hoursAhead(6),
    teams: ['West Indies', 'Afghanistan'],
    teamInfo: [t('WI'), t('AFG')],
    score: [],
    series_id: 'mock-series-5',
    seriesName: 'WI vs AFG T20I Series',
    matchStarted: false,
    matchEnded: false,
  },
  {
    id: 'mock-upcoming-3',
    name: 'Ireland vs Zimbabwe, 1st T20I',
    matchType: 'T20I',
    status: 'Match starts tomorrow',
    venue: 'Malahide, Dublin',
    date: hoursAhead(20),
    dateTimeGMT: hoursAhead(20),
    teams: ['Ireland', 'Zimbabwe'],
    teamInfo: [t('IRE'), t('ZIM')],
    score: [],
    series_id: 'mock-series-6',
    seriesName: 'IRE vs ZIM T20I Series',
    matchStarted: false,
    matchEnded: false,
  },
  {
    id: 'mock-finished-1',
    name: 'India vs England, 4th Test',
    matchType: 'Test',
    status: 'India won by an innings and 36 runs',
    venue: 'Wankhede Stadium, Mumbai',
    date: hoursAgo(48),
    dateTimeGMT: hoursAgo(48),
    teams: ['India', 'England'],
    teamInfo: [t('IND'), t('ENG')],
    score: [
      { r: 561, w: 8, o: 142, inning: 'India 1st Innings' },
      { r: 246, w: 10, o: 68.4, inning: 'England 1st Innings' },
      { r: 279, w: 10, o: 78.1, inning: 'England 2nd Innings' },
    ],
    series_id: 'mock-series-7',
    seriesName: 'India vs England Test Series',
    matchStarted: true,
    matchEnded: true,
  },
  {
    id: 'mock-finished-2',
    name: 'Australia vs New Zealand, 3rd T20I',
    matchType: 'T20I',
    status: 'Australia won by 7 wickets',
    venue: 'SCG, Sydney',
    date: hoursAgo(36),
    dateTimeGMT: hoursAgo(36),
    teams: ['Australia', 'New Zealand'],
    teamInfo: [t('AUS'), t('NZ')],
    score: [
      { r: 154, w: 8, o: 20, inning: 'New Zealand Innings' },
      { r: 156, w: 3, o: 17.2, inning: 'Australia Innings' },
    ],
    series_id: 'mock-series-8',
    seriesName: 'Trans-Tasman T20I Series',
    matchStarted: true,
    matchEnded: true,
  },
  {
    id: 'mock-finished-3',
    name: 'Pakistan vs South Africa, 2nd ODI',
    matchType: 'ODI',
    status: 'South Africa won by 4 wickets',
    venue: 'Gaddafi Stadium, Lahore',
    date: hoursAgo(60),
    dateTimeGMT: hoursAgo(60),
    teams: ['Pakistan', 'South Africa'],
    teamInfo: [t('PAK'), t('SA')],
    score: [
      { r: 264, w: 10, o: 49.2, inning: 'Pakistan Innings' },
      { r: 265, w: 6, o: 48.3, inning: 'South Africa Innings' },
    ],
    series_id: 'mock-series-9',
    seriesName: 'PAK vs SA ODI Series',
    matchStarted: true,
    matchEnded: true,
  },
];

// Per-match detailed scorecard (used by matchInfo endpoint)
const SCORECARDS = {
  'mock-live-1': {
    scorecard: [
      {
        inning: 'Australia Innings',
        batting: [
          { batsman: { name: 'D Warner' }, r: 78, b: 84, '4s': 8, '6s': 1, sr: 92.85, 'dismissal-text': 'c Kohli b Bumrah' },
          { batsman: { name: 'S Smith' }, r: 65, b: 71, '4s': 5, '6s': 0, sr: 91.55, 'dismissal-text': 'lbw b Jadeja' },
          { batsman: { name: 'G Maxwell' }, r: 56, b: 38, '4s': 4, '6s': 3, sr: 147.36, 'dismissal-text': 'c & b Chahal' },
          { batsman: { name: 'M Marsh' }, r: 41, b: 35, '4s': 3, '6s': 1, sr: 117.14, 'dismissal-text': 'run out (Iyer)' },
          { batsman: { name: 'A Carey' }, r: 22, b: 18, '4s': 2, '6s': 0, sr: 122.22, 'dismissal-text': 'not out' },
        ],
        bowling: [
          { bowler: { name: 'J Bumrah' }, o: 10, m: 1, r: 48, w: 3, eco: 4.80 },
          { bowler: { name: 'M Shami' }, o: 10, m: 0, r: 62, w: 2, eco: 6.20 },
          { bowler: { name: 'R Jadeja' }, o: 10, m: 0, r: 55, w: 2, eco: 5.50 },
          { bowler: { name: 'Y Chahal' }, o: 10, m: 0, r: 64, w: 1, eco: 6.40 },
          { bowler: { name: 'H Pandya' }, o: 10, m: 0, r: 58, w: 1, eco: 5.80 },
        ],
      },
      {
        inning: 'India Innings',
        batting: [
          { batsman: { name: 'R Sharma' }, r: 87, b: 89, '4s': 9, '6s': 2, sr: 97.75, 'dismissal-text': 'c Carey b Starc' },
          { batsman: { name: 'V Kohli' }, r: 72, b: 78, '4s': 6, '6s': 1, sr: 92.30, 'dismissal-text': 'lbw b Cummins' },
          { batsman: { name: 'S Iyer' }, r: 28, b: 35, '4s': 2, '6s': 0, sr: 80.00, 'dismissal-text': 'c Smith b Zampa' },
          { batsman: { name: 'KL Rahul' }, r: 19, b: 22, '4s': 1, '6s': 0, sr: 86.36, 'dismissal-text': 'b Hazlewood' },
          { batsman: { name: 'H Pandya' }, r: 12, b: 9, '4s': 1, '6s': 1, sr: 133.33, 'dismissal-text': 'not out' },
        ],
        bowling: [
          { bowler: { name: 'M Starc' }, o: 9, m: 0, r: 54, w: 2, eco: 6.00 },
          { bowler: { name: 'P Cummins' }, o: 9, m: 1, r: 41, w: 2, eco: 4.55 },
          { bowler: { name: 'J Hazlewood' }, o: 9, m: 0, r: 49, w: 1, eco: 5.44 },
          { bowler: { name: 'A Zampa' }, o: 9, m: 0, r: 52, w: 1, eco: 5.77 },
        ],
      },
    ],
    tossWinner: 'Australia',
    tossChoice: 'bat',
    matchWinner: '',
  },
  'mock-finished-1': {
    scorecard: [
      {
        inning: 'India 1st Innings',
        batting: [
          { batsman: { name: 'Y Jaiswal' }, r: 209, b: 290, '4s': 19, '6s': 7, sr: 72.06, 'dismissal-text': 'c Root b Anderson' },
          { batsman: { name: 'R Sharma' }, r: 131, b: 196, '4s': 14, '6s': 3, sr: 66.83, 'dismissal-text': 'b Bashir' },
          { batsman: { name: 'S Gill' }, r: 89, b: 138, '4s': 9, '6s': 2, sr: 64.49, 'dismissal-text': 'lbw b Hartley' },
        ],
        bowling: [
          { bowler: { name: 'J Anderson' }, o: 28, m: 6, r: 78, w: 2, eco: 2.78 },
          { bowler: { name: 'S Bashir' }, o: 38, m: 4, r: 142, w: 3, eco: 3.73 },
        ],
      },
      {
        inning: 'England 1st Innings',
        batting: [
          { batsman: { name: 'Z Crawley' }, r: 56, b: 73, '4s': 7, '6s': 0, sr: 76.71, 'dismissal-text': 'lbw b Ashwin' },
          { batsman: { name: 'J Root' }, r: 48, b: 89, '4s': 5, '6s': 0, sr: 53.93, 'dismissal-text': 'c Pant b Jadeja' },
        ],
        bowling: [
          { bowler: { name: 'R Ashwin' }, o: 22, m: 4, r: 56, w: 4, eco: 2.54 },
          { bowler: { name: 'R Jadeja' }, o: 18, m: 5, r: 38, w: 3, eco: 2.11 },
        ],
      },
    ],
    tossWinner: 'India',
    tossChoice: 'bat',
    matchWinner: 'India',
  },
};

// Points tables / standings
const SERIES = [
  {
    id: 'mock-series-1',
    name: 'Border-Gavaskar ODI Series 2024',
    startDate: hoursAgo(72),
    endDate: hoursAhead(72),
    odi: 3,
    t20: 0,
    test: 0,
    squads: 2,
    matches: 3,
  },
  {
    id: 'mock-series-7',
    name: 'India vs England Test Series 2024',
    startDate: hoursAgo(720),
    endDate: hoursAgo(24),
    odi: 0,
    t20: 0,
    test: 5,
    squads: 2,
    matches: 5,
  },
  {
    id: 'icc-wtc-25',
    name: 'ICC World Test Championship 2023-25',
    startDate: hoursAgo(8760),
    endDate: hoursAhead(2160),
    odi: 0,
    t20: 0,
    test: 27,
    squads: 9,
    matches: 27,
  },
];

const POINTS_TABLE = {
  'icc-wtc-25': [
    { team: 'Australia', shortname: 'AUS', matches: 14, wins: 9, loss: 3, draw: 0, ties: 0, no_result: 2, points: 110, net_run_rate: '+1.42' },
    { team: 'India', shortname: 'IND', matches: 15, wins: 8, loss: 5, draw: 0, ties: 0, no_result: 2, points: 104, net_run_rate: '+1.18' },
    { team: 'New Zealand', shortname: 'NZ', matches: 11, wins: 5, loss: 5, draw: 0, ties: 0, no_result: 1, points: 60, net_run_rate: '+0.24' },
    { team: 'England', shortname: 'ENG', matches: 17, wins: 8, loss: 8, draw: 0, ties: 0, no_result: 1, points: 88, net_run_rate: '-0.06' },
    { team: 'South Africa', shortname: 'SA', matches: 9, wins: 6, loss: 3, draw: 0, ties: 0, no_result: 0, points: 72, net_run_rate: '+0.94' },
    { team: 'Pakistan', shortname: 'PAK', matches: 12, wins: 4, loss: 7, draw: 0, ties: 0, no_result: 1, points: 50, net_run_rate: '-0.45' },
    { team: 'Sri Lanka', shortname: 'SL', matches: 9, wins: 3, loss: 6, draw: 0, ties: 0, no_result: 0, points: 36, net_run_rate: '-0.80' },
    { team: 'West Indies', shortname: 'WI', matches: 9, wins: 2, loss: 6, draw: 0, ties: 0, no_result: 1, points: 24, net_run_rate: '-1.20' },
    { team: 'Bangladesh', shortname: 'BAN', matches: 12, wins: 4, loss: 8, draw: 0, ties: 0, no_result: 0, points: 45, net_run_rate: '-0.62' },
  ],
};

const PLAYERS = {
  'mock-player-1': {
    id: 'mock-player-1',
    name: 'Virat Kohli',
    country: 'India',
    role: 'Batsman',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm medium',
    placeOfBirth: 'Delhi, India',
    dateOfBirth: '1988-11-05',
    image: 'https://flagcdn.com/w160/in.png',
    stats: [
      { fn: 'batting', matchtype: 'Test', stat: 'm', value: '113' },
      { fn: 'batting', matchtype: 'Test', stat: 'runs', value: '8848' },
      { fn: 'batting', matchtype: 'Test', stat: 'avg', value: '49.15' },
      { fn: 'batting', matchtype: 'Test', stat: '100', value: '29' },
      { fn: 'batting', matchtype: 'ODI', stat: 'm', value: '292' },
      { fn: 'batting', matchtype: 'ODI', stat: 'runs', value: '13848' },
      { fn: 'batting', matchtype: 'ODI', stat: 'avg', value: '58.18' },
      { fn: 'batting', matchtype: 'ODI', stat: '100', value: '50' },
    ],
  },
  'mock-player-2': {
    id: 'mock-player-2',
    name: 'Joe Root',
    country: 'England',
    role: 'Batsman',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm offbreak',
    placeOfBirth: 'Sheffield, England',
    dateOfBirth: '1990-12-30',
    image: 'https://flagcdn.com/w160/gb-eng.png',
    stats: [
      { fn: 'batting', matchtype: 'Test', stat: 'm', value: '143' },
      { fn: 'batting', matchtype: 'Test', stat: 'runs', value: '12027' },
      { fn: 'batting', matchtype: 'Test', stat: 'avg', value: '50.32' },
      { fn: 'batting', matchtype: 'Test', stat: '100', value: '32' },
    ],
  },
  'mock-player-3': {
    id: 'mock-player-3',
    name: 'Pat Cummins',
    country: 'Australia',
    role: 'Bowler',
    battingStyle: 'Right Handed Bat',
    bowlingStyle: 'Right-arm fast',
    placeOfBirth: 'Sydney, Australia',
    dateOfBirth: '1993-05-08',
    image: 'https://flagcdn.com/w160/au.png',
    stats: [
      { fn: 'bowling', matchtype: 'Test', stat: 'm', value: '62' },
      { fn: 'bowling', matchtype: 'Test', stat: 'wkts', value: '275' },
      { fn: 'bowling', matchtype: 'Test', stat: 'avg', value: '22.51' },
      { fn: 'bowling', matchtype: 'Test', stat: 'eco', value: '2.83' },
    ],
  },
};

const PLAYER_LIST = Object.values(PLAYERS).map((p) => ({
  id: p.id,
  name: p.name,
  country: p.country,
}));

module.exports = {
  MATCHES,
  SCORECARDS,
  SERIES,
  POINTS_TABLE,
  PLAYERS,
  PLAYER_LIST,
  generatedAt: now,
};
